function validArray(values){return Array.isArray(values)&&values.length>=1&&values.length<=12&&values.every((v,i)=>Number.isInteger(v)&&v>=-99&&v<=999&&(i===0||values[i-1]<v));}
function searchSteps(values,target){const steps=[];let left=0,right=values.length-1;while(left<=right){const mid=Math.floor((left+right)/2);steps.push({left,right,mid,found:values[mid]===target});if(values[mid]===target)return steps;if(values[mid]<target)left=mid+1;else right=mid-1;}steps.push({left,right,mid:null,found:false});return steps;}
createLearningActivity({
  scenes:window.LESSON_SCENES,
  restore:raw=>({values:validArray(raw.values)?raw.values:[2,5,8,12,17,23,31,40],target:Number.isInteger(raw.target)&&raw.target>=-99&&raw.target<=999?raw.target:23,step:Number.isInteger(raw.step)?Math.max(0,Math.min(4,raw.step)):0}),
  reset: state => { state.step = 0; },
  render:function renderSearch(node,state,scene,save){
    const steps=searchSteps(state.values,state.target);state.step=Math.min(steps.length-1,state.step);const current=steps[state.step];
    node.innerHTML=`<div class="controls"><label>严格递增数组 <input id="values" value="${state.values.join(', ')}"></label><label>目标 <input id="target" type="number" min="-99" max="999" value="${state.target}"></label><button id="apply">应用参数</button></div><p id="parameter-error" role="alert"></p><div class="chips">${state.values.map((n,i)=>`<div class="chip ${i===current.mid?'active':''} ${i<current.left||i>current.right?'eliminated':''}"><strong>${n}</strong><small style="display:block">下标 ${i}</small></div>`).join('')}</div><p class="result">left = ${current.left} · right = ${current.right} · mid = ${current.mid===null?'—':current.mid}</p><p class="summary">${current.mid===null?'区间为空：目标不存在。':current.found?`找到目标 ${state.target}，下标为 ${current.mid}。`:state.values[current.mid]<state.target?'中间元素比目标小，下一步排除左半部分。':'中间元素比目标大，下一步排除右半部分。'}</p><div class="controls"><button id="next" class="primary" ${state.step>=steps.length-1?'disabled':''}>下一次比较</button><button id="reset">重新查找</button></div><p class="notice">已显示 ${Math.min(state.step+1,steps.filter(s=>s.mid!==null).length)} 次比较。长度最多 12；未排序或重复的输入会提示修正。</p>`;
    node.querySelector('#next').onclick=()=>{state.step=Math.min(steps.length-1,state.step+1);renderSearch(node,state,scene,save);void save();};
    node.querySelector('#reset').onclick=async()=>{if(state.step>0&&!await confirmLearningReset('重新查找会清除当前比较进度，确定继续吗？'))return;state.step=0;renderSearch(node,state,scene,save);void save();};
    node.querySelector('#apply').onclick=async()=>{const text=node.querySelector('#values').value.trim();const values=text?text.split(/[,，\s]+/).map(Number):[];const target=Number(node.querySelector('#target').value);if(!validArray(values)||!Number.isInteger(target)||target<-99||target>999){node.querySelector('#parameter-error').textContent='请输入 1—12 个严格递增整数，数值与目标范围为 -99—999。';return;}if(state.step>0&&!await confirmLearningReset('应用参数会清除当前比较进度，确定继续吗？'))return;state.values=values;state.target=target;state.step=0;renderSearch(node,state,scene,save);void save();};
  },
}).catch(error=>{document.getElementById('activity-error').textContent=error.message;});
